#!/bin/bash

# --------- remote
remote="alphaboi@curtisnewbie.com"
remote_build_path="~/services/vfm/build/"
remote_config_path="~/services/vfm/config/"
# ---------

ssh  "alphaboi@curtisnewbie.com" "rm -rv ${remote_build_path}*"

scp -r ./* "${remote}:${remote_build_path}"
if [ ! $? -eq 0 ]; then
    exit -1
fi

scp ./app-conf-prod.yml "${remote}:${remote_config_path}"
if [ ! $? -eq 0 ]; then
    exit -1
fi

ssh  "alphaboi@curtisnewbie.com" "cd services; docker-compose up -d --build vfm"
