FROM alpine:3.17

LABEL author="Yongjie Zhuang"
LABEL descrption="vfm - Virtual File Manager"

RUN apk --no-cache add tzdata

WORKDIR /usr/src/

# binary is pre-compiled
COPY vfm_build ./app_vfm

ENV TZ=Asia/Shanghai

CMD ["./app_vfm", "configFile=/usr/src/config/conf.yml"]
