mode.production: true

app.name: "vfm"

mysql:
  enabled: true
  user: "${mysqlusername}"
  password: "${mysqlpassword}"
  database: "fileserver"
  host: "${mysqladdr}"
  port: 3306

redis:
  enabled: true
  address: "redis"
  port: 6379
  username:
  password:
  database: 0

server:
  web.enabled: true
  host: "0.0.0.0"
  port: 8086

consul:
  enabled: true
  consulAddress: consul:8500
  healthCheckUrl: /health

rabbitmq:
  enabled: true
  host: "rabbitmq"
  port: 5672
  username: "${rabbitmqusername}"
  password: "${rabbitmqpassword}"
  vhost: "/"

logging:
  rolling.file: "/usr/src/logs/vfm.log"
  level: info

goauth:
  client:
    enabled: true